#!/bin/bash

# activate the antiSMASH python environment
source /home/Bioinformatics_programs/antiSMASH/asenv/bin/activate

# Make directory
mkdir antiSMASH_output

# Run antiSMASH on a bacterial MAG
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0001 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0001 --html-title rhizo_MAG_0001 final_MAGs/rhizo_MAG_0001.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0002 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0002 --html-title rhizo_MAG_0002 final_MAGs/rhizo_MAG_0002.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0003 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0003 --html-title rhizo_MAG_0003 final_MAGs/rhizo_MAG_0003.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0004 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0004 --html-title rhizo_MAG_0004 final_MAGs/rhizo_MAG_0004.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0005 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0005 --html-title rhizo_MAG_0005 final_MAGs/rhizo_MAG_0005.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0006 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0006 --html-title rhizo_MAG_0006 final_MAGs/rhizo_MAG_0006.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0007 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0007 --html-title rhizo_MAG_0007 final_MAGs/rhizo_MAG_0007.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0008 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0008 --html-title rhizo_MAG_0008 final_MAGs/rhizo_MAG_0008.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0009 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0009 --html-title rhizo_MAG_0009 final_MAGs/rhizo_MAG_0009.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0010 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0010 --html-title rhizo_MAG_0010 final_MAGs/rhizo_MAG_0010.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0011 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0011 --html-title rhizo_MAG_0011 final_MAGs/rhizo_MAG_0011.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0012 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0012 --html-title rhizo_MAG_0012 final_MAGs/rhizo_MAG_0012.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0013 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0013 --html-title rhizo_MAG_0013 final_MAGs/rhizo_MAG_0013.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0014 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0014 --html-title rhizo_MAG_0014 final_MAGs/rhizo_MAG_0014.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0015 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0015 --html-title rhizo_MAG_0015 final_MAGs/rhizo_MAG_0015.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0016 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0016 --html-title rhizo_MAG_0016 final_MAGs/rhizo_MAG_0016.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0017 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0017 --html-title rhizo_MAG_0017 final_MAGs/rhizo_MAG_0017.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0018 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0018 --html-title rhizo_MAG_0018 final_MAGs/rhizo_MAG_0018.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0019 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0019 --html-title rhizo_MAG_0019 final_MAGs/rhizo_MAG_0019.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0020 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0020 --html-title rhizo_MAG_0020 final_MAGs/rhizo_MAG_0020.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0021 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0021 --html-title rhizo_MAG_0021 final_MAGs/rhizo_MAG_0021.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0022 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0022 --html-title rhizo_MAG_0022 final_MAGs/rhizo_MAG_0022.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0023 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0023 --html-title rhizo_MAG_0023 final_MAGs/rhizo_MAG_0023.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0024 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0024 --html-title rhizo_MAG_0024 final_MAGs/rhizo_MAG_0024.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0025 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0025 --html-title rhizo_MAG_0025 final_MAGs/rhizo_MAG_0025.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0026 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0026 --html-title rhizo_MAG_0026 final_MAGs/rhizo_MAG_0026.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0027 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0027 --html-title rhizo_MAG_0027 final_MAGs/rhizo_MAG_0027.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0028 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0028 --html-title rhizo_MAG_0028 final_MAGs/rhizo_MAG_0028.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0029 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0029 --html-title rhizo_MAG_0029 final_MAGs/rhizo_MAG_0029.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0030 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0030 --html-title rhizo_MAG_0030 final_MAGs/rhizo_MAG_0030.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0031 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0031 --html-title rhizo_MAG_0031 final_MAGs/rhizo_MAG_0031.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0032 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0032 --html-title rhizo_MAG_0032 final_MAGs/rhizo_MAG_0032.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0033 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0033 --html-title rhizo_MAG_0033 final_MAGs/rhizo_MAG_0033.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0034 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0034 --html-title rhizo_MAG_0034 final_MAGs/rhizo_MAG_0034.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0035 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0035 --html-title rhizo_MAG_0035 final_MAGs/rhizo_MAG_0035.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0036 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0036 --html-title rhizo_MAG_0036 final_MAGs/rhizo_MAG_0036.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0037 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0037 --html-title rhizo_MAG_0037 final_MAGs/rhizo_MAG_0037.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0038 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0038 --html-title rhizo_MAG_0038 final_MAGs/rhizo_MAG_0038.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0039 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0039 --html-title rhizo_MAG_0039 final_MAGs/rhizo_MAG_0039.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0040 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0040 --html-title rhizo_MAG_0040 final_MAGs/rhizo_MAG_0040.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0041 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0041 --html-title rhizo_MAG_0041 final_MAGs/rhizo_MAG_0041.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0042 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0042 --html-title rhizo_MAG_0042 final_MAGs/rhizo_MAG_0042.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0043 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0043 --html-title rhizo_MAG_0043 final_MAGs/rhizo_MAG_0043.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0044 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0044 --html-title rhizo_MAG_0044 final_MAGs/rhizo_MAG_0044.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_MAG_0045 --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_MAG_0045 --html-title rhizo_MAG_0045 final_MAGs/rhizo_MAG_0045.fasta
