#!/bin/bash

# Run antiSMASH on assemblies (bacterial)
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_Control_B2_0.5K --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_Control_B2_0.5K --html-title rhizo_Control_B2_0.5K reduced_assemblies/rhizo_Control_B2_0.5K.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_Control_B3_0.5K --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_Control_B3_0.5K --html-title rhizo_Control_B3_0.5K reduced_assemblies/rhizo_Control_B3_0.5K.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_Control_B4_0.5K --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_Control_B4_0.5K --html-title rhizo_Control_B4_0.5K reduced_assemblies/rhizo_Control_B4_0.5K.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_Control_B5_0.5K --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_Control_B5_0.5K --html-title rhizo_Control_B5_0.5K reduced_assemblies/rhizo_Control_B5_0.5K.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_R1P1_0.5K --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_R1P1_0.5K --html-title rhizo_R1P1_0.5K reduced_assemblies/rhizo_R1P1_0.5K.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_R1P5_0.5K --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_R1P5_0.5K --html-title rhizo_R1P5_0.5K reduced_assemblies/rhizo_R1P5_0.5K.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_R1P9_0.5K --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_R1P9_0.5K --html-title rhizo_R1P9_0.5K reduced_assemblies/rhizo_R1P9_0.5K.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_R1P14_0.5K --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_R1P14_0.5K --html-title rhizo_R1P14_0.5K reduced_assemblies/rhizo_R1P14_0.5K.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_R1P18_0.5K --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_R1P18_0.5K --html-title rhizo_R1P18_0.5K reduced_assemblies/rhizo_R1P18_0.5K.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_R3P3_0.5K --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_R3P3_0.5K --html-title rhizo_R3P3_0.5K reduced_assemblies/rhizo_R3P3_0.5K.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_R3P5_0.5K --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_R3P5_0.5K --html-title rhizo_R3P5_0.5K reduced_assemblies/rhizo_R3P5_0.5K.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_R3P11_0.5K --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_R3P11_0.5K --html-title rhizo_R3P11_0.5K reduced_assemblies/rhizo_R3P11_0.5K.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_R3P15_0.5K --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_R3P15_0.5K --html-title rhizo_R3P15_0.5K reduced_assemblies/rhizo_R3P15_0.5K.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_R3P20_0.5K --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_R3P20_0.5K --html-title rhizo_R3P20_0.5K reduced_assemblies/rhizo_R3P20_0.5K.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_R3P9_neg_0.5K --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_R3P9_neg_0.5K --html-title rhizo_R3P9_neg_0.5K reduced_assemblies/rhizo_R3P9_neg_0.5K.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_R3P10_neg_0.5K --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_R3P10_neg_0.5K --html-title rhizo_R3P10_neg_0.5K reduced_assemblies/rhizo_R3P10_neg_0.5K.fasta 
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_R3P12_neg_0.5K --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_R3P12_neg_0.5K --html-title rhizo_R3P12_neg_0.5K reduced_assemblies/rhizo_R3P12_neg_0.5K.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_R3P14_neg_0.5K --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_R3P14_neg_0.5K --html-title rhizo_R3P14_neg_0.5K reduced_assemblies/rhizo_R3P14_neg_0.5K.fasta
antismash --cpus 16 --taxon bacteria --genefinding-tool prodigal --output-dir antiSMASH_output/rhizo_R3P18_neg_0.5K --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --rre --tfbs --smcog-trees --asf --pfam2go --tigrfam --fullhmmer --output-basename rhizo_R3P18_neg_0.5K --html-title rhizo_R3P18_neg_0.5K reduced_assemblies/rhizo_R3P18_neg_0.5K.fasta