#!/bin/bash
#SBATCH --time=48:00:00
#SBATCH --account=def-gd38
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem-per-cpu=3500M

# Hazelnut Rhizosphere Dataset 1

java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.39.jar PE -threads 32 bbduk_output/rhizo_Control_B2_R1.bbduk.fastq.gz bbduk_output/rhizo_Control_B2_R2.bbduk.fastq.gz trimmomatic_output/rhizo_Control_B2_R1.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_Control_B2_R1.bbduk.unpaired.fastq.gz trimmomatic_output/rhizo_Control_B2_R2.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_Control_B2_R2.bbduk.unpaired.fastq.gz LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.39.jar PE -threads 32 bbduk_output/rhizo_Control_B3_R1.bbduk.fastq.gz bbduk_output/rhizo_Control_B3_R2.bbduk.fastq.gz trimmomatic_output/rhizo_Control_B3_R1.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_Control_B3_R1.bbduk.unpaired.fastq.gz trimmomatic_output/rhizo_Control_B3_R2.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_Control_B3_R2.bbduk.unpaired.fastq.gz LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.39.jar PE -threads 32 bbduk_output/rhizo_Control_B5_R1.bbduk.fastq.gz bbduk_output/rhizo_Control_B5_R2.bbduk.fastq.gz trimmomatic_output/rhizo_Control_B5_R1.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_Control_B5_R1.bbduk.unpaired.fastq.gz trimmomatic_output/rhizo_Control_B5_R2.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_Control_B5_R2.bbduk.unpaired.fastq.gz LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.39.jar PE -threads 32 bbduk_output/rhizo_R1P14_R1.bbduk.fastq.gz bbduk_output/rhizo_R1P14_R2.bbduk.fastq.gz trimmomatic_output/rhizo_R1P14_R1.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R1P14_R1.bbduk.unpaired.fastq.gz trimmomatic_output/rhizo_R1P14_R2.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R1P14_R2.bbduk.unpaired.fastq.gz LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.39.jar PE -threads 32 bbduk_output/rhizo_R1P5_R1.bbduk.fastq.gz bbduk_output/rhizo_R1P5_R2.bbduk.fastq.gz trimmomatic_output/rhizo_R1P5_R1.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R1P5_R1.bbduk.unpaired.fastq.gz trimmomatic_output/rhizo_R1P5_R2.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R1P5_R2.bbduk.unpaired.fastq.gz LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.39.jar PE -threads 32 bbduk_output/rhizo_R1P9_R1.bbduk.fastq.gz bbduk_output/rhizo_R1P9_R2.bbduk.fastq.gz trimmomatic_output/rhizo_R1P9_R1.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R1P9_R1.bbduk.unpaired.fastq.gz trimmomatic_output/rhizo_R1P9_R2.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R1P9_R2.bbduk.unpaired.fastq.gz LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.39.jar PE -threads 32 bbduk_output/rhizo_R3P10_neg_R1.bbduk.fastq.gz bbduk_output/rhizo_R3P10_neg_R2.bbduk.fastq.gz trimmomatic_output/rhizo_R3P10_neg_R1.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R3P10_neg_R1.bbduk.unpaired.fastq.gz trimmomatic_output/rhizo_R3P10_neg_R2.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R3P10_neg_R2.bbduk.unpaired.fastq.gz LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.39.jar PE -threads 32 bbduk_output/rhizo_R3P12_neg_R1.bbduk.fastq.gz bbduk_output/rhizo_R3P12_neg_R2.bbduk.fastq.gz trimmomatic_output/rhizo_R3P12_neg_R1.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R3P12_neg_R1.bbduk.unpaired.fastq.gz trimmomatic_output/rhizo_R3P12_neg_R2.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R3P12_neg_R2.bbduk.unpaired.fastq.gz LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.39.jar PE -threads 32 bbduk_output/rhizo_R3P15_R1.bbduk.fastq.gz bbduk_output/rhizo_R3P15_R2.bbduk.fastq.gz trimmomatic_output/rhizo_R3P15_R1.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R3P15_R1.bbduk.unpaired.fastq.gz trimmomatic_output/rhizo_R3P15_R2.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R3P15_R2.bbduk.unpaired.fastq.gz LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.39.jar PE -threads 32 bbduk_output/rhizo_R3P20_R1.bbduk.fastq.gz bbduk_output/rhizo_R3P20_R2.bbduk.fastq.gz trimmomatic_output/rhizo_R3P20_R1.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R3P20_R1.bbduk.unpaired.fastq.gz trimmomatic_output/rhizo_R3P20_R2.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R3P20_R2.bbduk.unpaired.fastq.gz LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.39.jar PE -threads 32 bbduk_output/rhizo_R3P3_R1.bbduk.fastq.gz bbduk_output/rhizo_R3P3_R2.bbduk.fastq.gz trimmomatic_output/rhizo_R3P3_R1.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R3P3_R1.bbduk.unpaired.fastq.gz trimmomatic_output/rhizo_R3P3_R2.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R3P3_R2.bbduk.unpaired.fastq.gz LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.39.jar PE -threads 32 bbduk_output/rhizo_R3P9_neg_R1.bbduk.fastq.gz bbduk_output/rhizo_R3P9_neg_R2.bbduk.fastq.gz trimmomatic_output/rhizo_R3P9_neg_R1.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R3P9_neg_R1.bbduk.unpaired.fastq.gz trimmomatic_output/rhizo_R3P9_neg_R2.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R3P9_neg_R2.bbduk.unpaired.fastq.gz LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36

# Hazelnut Rhizosphere Dataset 2

java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.39.jar PE -threads 32 bbduk_output/rhizo_Control_B4_R1.bbduk.fastq.gz bbduk_output/rhizo_Control_B4_R2.bbduk.fastq.gz trimmomatic_output/rhizo_Control_B4_R1.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_Control_B4_R1.bbduk.unpaired.fastq.gz trimmomatic_output/rhizo_Control_B4_R2.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_Control_B4_R2.bbduk.unpaired.fastq.gz LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.39.jar PE -threads 32 bbduk_output/rhizo_R1P1_R1.bbduk.fastq.gz bbduk_output/rhizo_R1P1_R2.bbduk.fastq.gz trimmomatic_output/rhizo_R1P1_R1.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R1P1_R1.bbduk.unpaired.fastq.gz trimmomatic_output/rhizo_R1P1_R2.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R1P1_R2.bbduk.unpaired.fastq.gz LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.39.jar PE -threads 32 bbduk_output/rhizo_R1P18_R1.bbduk.fastq.gz bbduk_output/rhizo_R1P18_R2.bbduk.fastq.gz trimmomatic_output/rhizo_R1P18_R1.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R1P18_R1.bbduk.unpaired.fastq.gz trimmomatic_output/rhizo_R1P18_R2.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R1P18_R2.bbduk.unpaired.fastq.gz LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.39.jar PE -threads 32 bbduk_output/rhizo_R3P11_R1.bbduk.fastq.gz bbduk_output/rhizo_R3P11_R2.bbduk.fastq.gz trimmomatic_output/rhizo_R3P11_R1.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R3P11_R1.bbduk.unpaired.fastq.gz trimmomatic_output/rhizo_R3P11_R2.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R3P11_R2.bbduk.unpaired.fastq.gz LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.39.jar PE -threads 32 bbduk_output/rhizo_R3P5_R1.bbduk.fastq.gz bbduk_output/rhizo_R3P5_R2.bbduk.fastq.gz trimmomatic_output/rhizo_R3P5_R1.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R3P5_R1.bbduk.unpaired.fastq.gz trimmomatic_output/rhizo_R3P5_R2.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R3P5_R2.bbduk.unpaired.fastq.gz LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.39.jar PE -threads 32 bbduk_output/rhizo_R3P14_neg_R1.bbduk.fastq.gz bbduk_output/rhizo_R3P14_neg_R2.bbduk.fastq.gz trimmomatic_output/rhizo_R3P14_neg_R1.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R3P14_neg_R1.bbduk.unpaired.fastq.gz trimmomatic_output/rhizo_R3P14_neg_R2.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R3P14_neg_R2.bbduk.unpaired.fastq.gz LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.39.jar PE -threads 32 bbduk_output/rhizo_R3P18_neg_R1.bbduk.fastq.gz bbduk_output/rhizo_R3P18_neg_R2.bbduk.fastq.gz trimmomatic_output/rhizo_R3P18_neg_R1.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R3P18_neg_R1.bbduk.unpaired.fastq.gz trimmomatic_output/rhizo_R3P18_neg_R2.bbduk.trimmed.fastq.gz trimmomatic_output/rhizo_R3P18_neg_R2.bbduk.unpaired.fastq.gz LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
